apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: atomic-update-agent
  namespace: reboot-coordinator
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: atomic-update-agent
    spec:
      serviceAccountName: default
      containers:
      - name: update-agent
        image: quay.io/spiketesting/atomic-update-operator:v0.0.0
        imagePullPolicy: IfNotPresent
        command:
        - "/bin/update-agent"
        securityContext:
          runAsUser: 0
          seLinuxOptions:
            type: "spc_t"
        volumeMounts:
          - mountPath: /var/run/dbus/
            name: var-run-dbus
          - mountPath: /etc/os-release
            name: etc-os-release
        env:
        # read by update-agent as the node name to manage reboots for
        - name: UPDATE_AGENT_NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      volumes:
      - name: var-run-dbus
        hostPath:
          path: /var/run/dbus/
      - name: etc-os-release
        hostPath:
          path: /etc/os-release
